site_name: test

repo_name: sekthor/repo-tmpl
repo_url: https://github.com/sekthor/repo-tmpl
edit_uri: edit/main/docs/

theme: 
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    # links on pages to view/edit md source on github
    - content.action.edit
    - content.action.view
  
  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
  
  #icon:
    # button to edit a page
    #edit: material/pencil 

    # button to view md source of page
    #view: material/eye
